title: <p align="center"> Amit Kumar Shukla </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/amit-kumar-shukla-82b54213/">LinkedIn</a> |
  <a href="https://github.com/shuklaamitk">GitHub</a>
  
  <br>   
Team Lead with 13 years of experience in varied applications and systems development/management, with proficiency in development of Web-based applications using Microsoft Technologies .
  <br>
  </p>



theme: jekyll-theme-minimal
